---

- name: Dependencies install
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - python3
      - python3-pip
    update_cache: true
    autoclean: true
    autoremove: true
  become: true

- name: Keyrigs directory exists
  ansible.builtin.file:
    path: "{{ docker_keyring_dir }}"
    state: directory
    owner: root
  become: true


- name: Add Docker repository GPT key
  ansible.builtin.apt_key:
    url: "{{ docker_gpg_key_url }}"
    keyring: "{{ docker_keyring }}"
    state: present
  become: true

- name: Register arch
  ansible.builtin.command:
    cmd: dpkg --print-architecture
  register: docker_arch
  changed_when: false

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ docker_arch.stdout }} signed-by={{ docker_keyring }}] {{ docker_repository_url }} {{ ansible_facts.distribution_release }} stable"
    state: present
    filename: docker.list
    update_cache: true
  become: true

- name: Docker packages installed
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    update_cache: true
    autoclean: true
    autoremove: true
  become: true
  notify:
    - docker_installed

- name: Create docker group
  ansible.builtin.group:
    name: docker
    state: present
  become: true

- name: Add current user to group docker
  ansible.builtin.user:
    name: "kirill"
    groups: "{{ docker_group_user }}"
    append: true
  become: true
  notify:
    - docker_user_add_to_group

- name: Docker python plugin installed
  ansible.builtin.pip:
    name:
      - docker
      - docker-compose
    break_system_packages: true
    state: present
